CC=cc
UNITY_INCLUDE=../Unity/src
UNITY_SRC=../Unity/src/unity.c

all: counting_sort counting_sort_func counting_sort_key

counting_sort:
	$(CC) -o $@ $@.c

counting_sort_func:
	$(CC) -o $@ $@.c

counting_sort_key:
	$(CC) -o $@ $@.c

clean:
	rm -f counting_sort counting_sort_func counting_sort_key
